### ISSUE TITLE
High level cp change

### ISSUE THREAD

**Issue by Alienater** [shiftcodeYT/PokeBot2#18]
I have missed two unknown cp dragonites (im level 24, so they must have been high). I think it would be a good idea to never dip below 20 raspberries and 20 ultra balls, so that if something rare like this comes up, we have enough to catch it. 

Does the bot use raspberries? For higher cp mons, i think it would be useful, but i have not seen it in the window yet.  It would be nice to choose when are the cutoff values for using regular, great, and ultra balls. 

Best

**Comment by shiftcodeYT** [comment]
Dupe #22
