### ISSUE TITLE
Multiple instance with google auth

### ISSUE THREAD

**Issue by ilikesomething** [shiftcodeYT/PokeBot2#24]
How can we launch multiple instance with different google accounts ?

If i copy the folder and delete the token.txt in the new folder and launch it will still connect to the previous google account

Do you have an idea?

**Comment by shiftcodeYT** [comment]
It certainly *should* work, but i don't know. Can you send screenshots of both folders?

**Comment by ilikesomething** [comment]
![screen](https://cloud.githubusercontent.com/assets/13218000/17077112/94198296-50c4-11e6-8314-32afbff6daf4.png)

here it is.

I tried to corrupt the token (by adding chars in it) or to delete the .txt but when i launch it still connect to the current connected account (used in folder 1)

**Comment by shiftcodeYT** [comment]
Well, that's odd. Can you try deleting token.txt in both folders?

**Comment by ilikesomething** [comment]
i tried an dit worked, i think its because of my shortcut (i did theses to be able to log in .txt,) and the target was the old one
