### ISSUE TITLE
Got away...

### ISSUE THREAD

**Issue by kmlalpr** [shiftcodeYT/PokeBot2#28]
My bot has %10 chance for Caught %90 chance got away . Im always seeing this "xxxx with 300 cp got away..." ALWAYS... Is there a fix for this?

**Comment by shiftcodeYT** [comment]
You are most likely softbanned.

**Comment by yashrs** [comment]
How to undo softbanned ?

**Comment by spot88** [comment]
Wait up to 30minutes and retry. Try to pick a spot where it's not far from pokestops.
