### ISSUE TITLE
something doesnt work

### ISSUE THREAD

**Issue by xeriix** [shiftcodeYT/PokeBot2#33]
farm pokstop and catch pokemons dosnt work for me in my old acc.

i create a new account for pokemon go and all works fine, but when i login with my old account of pokemon go, the farm pokestop and catch pokemons doesnt work.

any fix?

**Comment by houmik** [comment]
Maybe you get softban. Did you teleport somewhere ?

**Comment by xeriix** [comment]
Nop, i try in the app(pokemon go) and all is fine.

**Comment by shiftcodeYT** [comment]
He probably has done something wrong in his config. Softban 4 sure.
