### ISSUE TITLE
404 (German Error)  Release.zip 2.0.1

### ISSUE THREAD

**Issue by Blurline** [shiftcodeYT/PokeBot2#36]
Unbehandelte Ausnahme: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
   bei System.Net.HttpWebRequest.GetResponse()
   bei PokemonGo.RocketAPI.Console.Program.<ExecuteCatchAllNearbyPokemons>d__5.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot2\PokemonGo\RocketAPI\Console\Program.cs:Zeile 185.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PokemonGo.RocketAPI.Console.Program.<ExecuteFarmingPokestopsAndPokemons>d__6.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot2\PokemonGo\RocketAPI\Console\Program.cs:Zeile 227.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PokemonGo.RocketAPI.Console.Program.<Execute>d__4.MoveNext() in C:\Users\simon\Documents\GitHub\PokeBot2\PokemonGo\RocketAPI\Console\Program.cs:Zeile 142.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by AlexHolo** [comment]
I am receiving this too after a few seconds of running:
http://puu.sh/qc8Xr.png

**Comment by 1461748123** [comment]
Yes, the website the program used to get the german name from are down. Thats why this error poped up. I'm making a proper language system using xml to store names, hopefully I can commit that tonight and ShiftCode can view and accept the code

**Comment by shiftcodeYT** [comment]
@1461748123 i will :)

**Comment by shiftcodeYT** [comment]
Can be fixed by changing language to english. I'm closing this now, but Brian or I can implement a new language system.
