### ISSUE TITLE
Argument NULL Reference - Restarting

### ISSUE THREAD

**Issue by ZapZapBum** [shiftcodeYT/PokeBot2#37]
Im getting a spam of "Argument NULL Reference - Restarting"... any thoughts about why?

**Comment by ZapZapBum** [comment]
PS: Removing the token solves this shit :)

**Comment by supercar325** [comment]
yea but it's gonna happen again

**Comment by supercar325** [comment]
so we have to delete the "token" txt again

**Comment by 1461748123** [comment]
Shiftcode have already fixed the problem. You have to download the latest code and compile it by your self

**Comment by supercar325** [comment]
Is 2.0.1 a latest version, I did download it and the problem is still there, running the program for about an hour and "Argument NULL Reference - Restarting"... . So I have to delete " token.txt " everytime it has that problem :(

**Comment by 1461748123** [comment]
No, you have to download the code, not the release. Shiftcode haven't release it yet.

**Comment by supercar325** [comment]
uhmm can you help me how to compile it?

**Comment by 1461748123** [comment]
Use visual studio to compile the code, lots of tutorial online

**Comment by shiftcodeYT** [comment]
#13
