### ISSUE TITLE
Pokemon transferring blacklist/whitelist

### ISSUE THREAD

**Issue by kingkong91108** [shiftcodeYT/PokeBot2#38]
Is there any way to change the duplicate mode so we can choose how many we can have at a time for transferring? Because it literally transfers everything lower then your highest, i lose good high cp pokemon. For example i have 2 gyarados's and 1 of them is 2026 and the other is 1982. I can't choose duplicate mode because it will transfer my second gyarados and i cant choose the cp because it will sacrifice some low level rare pokemons and i cant use none because i need candy to evolve.
Also what does (TransferAllButStrongestUnwantedPokemon) do? I only want to transfer weak pokemon to evolve them and sometimes the bot transfers pidgeottos instead of pidgeys
I also see that there are whitelist and blacklist but no instructions on how to use them anywhere

**Comment by shiftcodeYT** [comment]
1)Use cp mode for limits, and set threshold for max
2)It's not yet available in the release. I'll fix that soon.
