### ISSUE TITLE
Catch Fail

### ISSUE THREAD

**Issue by cobalt00** [shiftcodeYT/PokeBot2#39]
some bug appeared not receiving any exp or items from PokeStop and every pokemon met ran away even with 16CP ratata
any idea to solve this? using the actual app still works fine
problem appear after Argument NULL Reference - Restarting thing then i delete the token and reconnect then the result is as above

**Comment by plum04** [comment]
Your account could be banned, or ur inventory is full

**Comment by cobalt00** [comment]
nope i'm playing on the app still fine and my inventory is not full

**Comment by shiftcodeYT** [comment]
You probably set your coords wrong. Either correct that or leave the bot for 15min then it should start working again.
