### ISSUE TITLE
Recycles Item pokeball when start.

### ISSUE THREAD

**Issue by kingsofcoms** [shiftcodeYT/PokeBot2#4]
When it runs a new thread it recycles item pokeballs, why?

Also can we implement transfer of pokemons with IVs below 85% instead of CP threshold.

**Comment by kingsofcoms** [comment]
Ok, found out that IVs is set to 80%. It would be better to keep the atleast 50 pokeballs at hand and dropping all potions.

**Comment by shiftcodeYT** [comment]
Will look at it. Thanks for your help!

**Comment by shiftcodeYT** [comment]
Done. Now it keeps as many pokeballs as it will need.
