### ISSUE TITLE
What is this? restarting..

### ISSUE THREAD

**Issue by Layzi** [shiftcodeYT/PokeBot2#49]
Hello, why sometimes is the message "(...) restarting .." and you have to unpack all over again because do not work terribly upset :(

**Comment by tunayuyar** [comment]
check this

https://github.com/shiftcodeYT/PokeBot2/issues/13#issuecomment-234772708

**Comment by Layzi** [comment]
million links, I can not understand :<

**Comment by tunayuyar** [comment]
Just download the zip file in my message.

**Comment by Layzi** [comment]
Okey i download this and play. works on 100%?
