### ISSUE TITLE
Recycling and customization.

### ISSUE THREAD

**Issue by robertkaroyan** [shiftcodeYT/PokeBot2#51]
Hi,

I love the Pokebot 2.0 but the customization is not very big. 
Would love to edit some codes, for example the recycle code. It recycles my items, but it removes important ones like great balls. I can recycle my items myself when the bag hits the max. amount of items. Or make a code where the bot recycles only when 80% of your bag is full.

Thanks!

**Comment by NullFlex** [comment]
I agree, it recycled all of my Revives and potions. Please fix.

**Comment by shiftcodeYT** [comment]
Done. Download newest release.
