### ISSUE TITLE
Feature Request -  Live Latitude from pokevision.com

### ISSUE THREAD

**Issue by Blurline** [shiftcodeYT/PokeBot2#55]
filter what kind of pokemon und get the current position^^ -> pokevision.com -> Change to Position in a radius - 5km/10km

**Comment by 1461748123** [comment]
Great idea!

**Comment by Blurline** [comment]
but i think it is possible to get the Information -> pokemon api. -> request every x sec 5km around you -> go to the location if the pokemon is on your list -> pathfinder ;)

**Comment by spot88** [comment]
This is not a good long term, you will get softbanned, a lot. @shiftcodeYT can say ye\ne do this.

**Comment by shiftcodeYT** [comment]
@spot88 yup, chance of softban = 100%. Good idea tho.
