### ISSUE TITLE
Latitude/Longitude Cords

### ISSUE THREAD

**Issue by dappy9** [shiftcodeYT/PokeBot2#59]
Like the idiot I am, I started the exe and it began transferring but then i realized I forgot the change the latitude/longitude cords
What is the original location of the cords?
Edit: is is possible to remove the recycling of certain items? I want to keep my pokeballs and super revives

**Comment by shiftcodeYT** [comment]
To find out the *original* location, view the external.config on github. The transfer filter is implemented now.
