### ISSUE TITLE
PokeBot Crash

### ISSUE THREAD

**Issue by sancturn** [shiftcodeYT/PokeBot2#60]
Error that I'm receiving:

`Logged in Google Account..
Successfully recieved token.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Extensions\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Text.Encoding\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Text.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Collections\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\Users\michael\Desktop\PokeBot2-master\PokemonGo.RocketAPI.Window\bin\Debug\S2Geometry.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PokemonGo.RocketAPI.Window.vshost.exe' (CLR v4.0.30319: PokemonGo.RocketAPI.Window.vshost.exe): Loaded 'C:\Users\michael\Desktop\PokeBot2-master\PokemonGo.RocketAPI.Window\bin\Debug\System.VarintBitConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0xfe8 has exited with code 0 (0x0).
The thread 0x23d4 has exited with code 0 (0x0).
The thread 0x15f8 has exited with code 0 (0x0).
The thread 0x3c30 has exited with code 0 (0x0).
`

Also getting:

`Request to web host unsuccessful: 'An error has occurred."`

`The thread 0x1c60 has exited with code 0 (0x0).`

`Exception thrown: 'System.UriFormatException' in System.dll
Exception thrown: 'System.UriFormatException' in mscorlib.dll
Exception thrown: 'System.UriFormatException' in mscorlib.dll
Exception thrown: 'System.UriFormatException' in mscorlib.dll`

Update New Errors:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0535	'Settings' does not implement interface member 'ISettings.ItemRecyclingCount'	PokemonGo.RocketAPI.Window	C:\Users\michael\Desktop\PokeBot2-master\PokemonGo.RocketAPI.Window\Settings.cs	15	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	PokemonGo.RocketAPI	C:\Users\michael\Desktop\PokeBot2-master\PokemonGo\RocketAPI\Client.cs	413	Active
`

**Comment by BukkitTNT** [comment]
Please download the actual version from the 'release' Page. Current build is: 2.1
