### ISSUE TITLE
pokestop

### ISSUE THREAD

**Issue by sgtsebas** [shiftcodeYT/PokeBot2#61]
hi, my bot dosent seem to get any item from the pokestop it said 0 xp 0 item ....
![sans titre](https://cloud.githubusercontent.com/assets/20633243/17089265/d7a8f2e2-51f2-11e6-98b3-60ede6cc7e12.jpg)

**Comment by ArtemDNK** [comment]
you account softbanned

**Comment by sgtsebas** [comment]
and how can i avoid this ? and my pokemongo still working verywell on my phone

**Comment by sgtsebas** [comment]
sorry for my bad english

**Comment by Deantje2016** [comment]
Most of the people say: wait 30 min. So try that out and most of the times it works. Did you change the lon and lat in a short time?

**Comment by sgtsebas** [comment]
yeah i changed the long and lat in a short time it was my bad sorry guys :P now it work perfectly its been running since 6 hrs got lot of shit haha
