### ISSUE TITLE
Pokemons issue

### ISSUE THREAD

**Issue by j4necki** [shiftcodeYT/PokeBot2#63]
Is anyone have same issue with not catching pokemons?
I'm not soft banned because i'm getting xp from pokestops but all pokemons runs away.
Even cp not showing up in console..
![poke](https://cloud.githubusercontent.com/assets/20641066/17101756/97b338f8-5276-11e6-8d67-09164d126c40.jpg)

**Comment by Blurline** [comment]
+1 -> 2.1 no softban

**Comment by kmlalpr** [comment]
[17:30:35] Clefairy with [cp] CP got away...

same to me

**Comment by Dellap** [comment]
check u pokemon in game, maybe full 225/225 pokemon. sorry my english is shit

**Comment by Dellap** [comment]
check u pokemon in game, maybe full 225/225 pokemon. sorry my english is shit

**Comment by sgtsebas** [comment]
turn off recycle item you ran out of pokeball happens to me yesterday

**Comment by Blurline** [comment]
Resolved? -> limit of pokemon

**Comment by spot88** [comment]
Closed, either full pokemon in game or 0 pokeballs.
