### ISSUE TITLE
thanks for the awesome job and continued his user friendly project

### ISSUE THREAD

**Issue by Luc4z** [shiftcodeYT/PokeBot2#7]
and if there's a XP mode in the futer , it should also capture pokemon too because with candy it can gain more exp .

also can you add evolve all pokemon in "leaveStrongest" list before transfer them ?
or just make a list for evolethemall

**Comment by shiftcodeYT** [comment]
I'll add a option. Thanks!

**Comment by kingsofcoms** [comment]
@Luc4z why would you want to evolve a pokemon if you're eventually gonna transfer them.

**Comment by shiftcodeYT** [comment]
@kingsofcoms XP

**Comment by kingsofcoms** [comment]
but doesn't evolve cost around 50 candies for some pokemons, thats a lot. Those candies could be used to powerup better IV pokemons though.

**Comment by shiftcodeYT** [comment]
@kingsofcoms ... just realized this is useless :P
