### ISSUE TITLE
Stopping after hatching egg.?

### ISSUE THREAD

**Issue by fededevi** [shiftcodeYT/PokeBot2#77]
So I noticed something strange but I'm not sure about it. 
I logged my account and incubated an egg (I had 9 eggs), logged out, started the bot and everything worked fine until the bot suddenly stopped. Nothing was written on the console, no crash, no errors.

I restarted it and it worked fine, and I noticed that at the first pokestop I got a new egg. 
So not 100% sure but maybe the bot stopped right after hatching the egg?

**Comment by Pepsai** [comment]
I dont think so.
I have been hatching eggs as well.

Did you remember to close down the bot before you entered the game on an emulator/phone?
I belive that could be the problem because then it would have been logged in from 2 diffrent devices.

**Comment by fededevi** [comment]
Yes I closed the emulator, and I logged in in the same spot to avoid problems. 
It might just be a coincidence.
I will try to repeat the process and confirm.

**Comment by fededevi** [comment]
TESTED:
I tested it 2 times and the bot did not stop this time. Closing
