### ISSUE TITLE
Love the bot one problem though

### ISSUE THREAD

**Issue by betrdenu** [shiftcodeYT/PokeBot2#8]
Everything is working great except for when the bot tries to catch pokemon it fails on everysingle one even the 150 cp pokemon ....did i do something wrong in setup?

**Comment by shiftcodeYT** [comment]
You either have a softban, or no pokeballs :)
Please check if you gain XP from pokestops or it simply says "PokeStop XP:0"

Thanks :)

**Comment by kingsofcoms** [comment]
most likely a softban.

i catch all pokemons, success rate around 95%.

**Comment by betrdenu** [comment]
nevermind it fixed itself the first7 or 8 it missed (and i know i have pokeballs i was just on it lol) but its catching the majority now

**Comment by shiftcodeYT** [comment]
ok then ;)

**Comment by betrdenu** [comment]
whered that close button go i feel silly and impatient now

**Comment by shiftcodeYT** [comment]
I closed it :P
