### ISSUE TITLE
restarting failed

### ISSUE THREAD

**Issue by sgtsebas** [shiftcodeYT/PokeBot2#80]
hi, my bot work fine for 1-2 hrs then it always said argument null reference - restarting 

then i need to delete all my folder and download a new one to make it work again 

 any idea ? 
![poke](https://cloud.githubusercontent.com/assets/20633243/17156490/238b83b2-5358-11e6-9c6d-17bc9e6e7fa6.jpg)

**Comment by Epsilith** [comment]
I believe this is a duplicate but...
All you have to do is delete your 'token.txt' file restart PokeBot.
