### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by N4MeD** [shiftcodeYT/PokeBot2#82]
I just reopened the programm and now there is this Error and  I dont know how to fix it.
I would like to change the language to english but i dont know how.
Every help is welcome :D.
![errorscreen](https://cloud.githubusercontent.com/assets/20688598/17187910/5be23402-543b-11e6-872a-d4762e3795c5.JPG)

**Comment by spot88** [comment]
Check your config file, and change to en

**Comment by N4MeD** [comment]
didnt work, but i think u can solve it anyway :D

**Comment by N4MeD** [comment]
Meanwhile I just restarted my Pc and nothing happend

**Comment by N4MeD** [comment]
At the top it says : cant reach accounts.google.com

**Comment by N4MeD** [comment]
After a few restarts it worked again. Thanks for the great program. Keep the good work going >D
