### ISSUE TITLE
Failed to initiate google login

### ISSUE THREAD

**Issue by shiraori** [shiftcodeYT/PokeBot2#85]
Recently I'm failed to initiate login with google account.

The device login code I got is blank.

http://i.imgur.com/pAJwdZ7.jpg

I'm using an unmodified release build.

**Comment by XibalbaTM** [comment]
some problem +1

**Comment by dedren** [comment]
Same issue, any way to resolve yet?

**Comment by afossey** [comment]
Same here

**Comment by daneil1999123** [comment]
same here

**Comment by Acerbytas** [comment]
Yep +1, please fix it soon ;)

**Comment by dedren** [comment]
Nevermind the server's are down.

**Comment by DasKristoff** [comment]
Same, hope this gets resolved soon. Hopefully it's all Google's fault and they'll get it in check

**Comment by conmcgu** [comment]
Any updates on when it's working

**Comment by conmcgu** [comment]
Any updates on when it's working
