### ISSUE TITLE
Pokebot Crash

### ISSUE THREAD

**Issue by sancturn** [shiftcodeYT/PokeBot2#86]
I'm not sure why I'm getting this error when attempting to run PokeBot2

`Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in mscorlib.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in mscorlib.dll
`

**Comment by kagasu** [comment]
Get ```Newtonsoft.Json``` from NuGet

**Comment by spot88** [comment]
And servers are down atm.
