### ISSUE TITLE
Bot not working ?

### ISSUE THREAD

**Issue by conmcgu** [shiftcodeYT/PokeBot2#88]
I'm struggling slightly aha, every time I run the bot it just says visit and click enter ? Have a missed a really obvious part and just being an idiot aha any help appreciated

**Comment by dantalion696** [comment]
its not working, the game is log in normally. Should be anything related with the way the bot logs in the server...

**Comment by conmcgu** [comment]
Just confused me more 😂

**Comment by Acerbytas** [comment]
I think it's an internal error of google auth.
It should have displayed:

"visit https://www.google.com/device and enter XXXX-XXXX"

please, fix this issue soon ;)

**Comment by shiftcodeYT** [comment]
Let me check.

**Comment by kagasu** [comment]
https://github.com/DetectiveSquirrel/Pokemon-Go-Rocket-API/pull/446

**Comment by Acerbytas** [comment]
Prooved: Ptc login WORKS, Google login NOPE.

(please fix google asap :) and thanks a lot for the work mate, really appreciated)
