### ISSUE TITLE
work bot?

### ISSUE THREAD

**Issue by NurdinA** [shiftcodeYT/PokeBot2#89]
Anybody can put the assembled working bot ?

**Comment by Acerbytas** [comment]
Prooved: Ptc login WORKS, Google login NOPE.

(please fix google asap :) and ty for the work mate, really appreciated.)

**Comment by pokemonbotter** [comment]
server are doing some changes no bots are working as of now

**Comment by pokemonbotter** [comment]
They changed the API the uploader will have to fix this the rocket API was changed just wait it will happen I hope :) I really like this coder btw
