### ISSUE TITLE
ERROR IN FIRST CLICK

### ISSUE THREAD

**Issue by zufar56** [shiftcodeYT/PokeBot2#90]
why i just get some msg '' Please Visit and Enter'' ?

**Comment by jackel66** [comment]
you have to use PTC login, google isnt working at the moment.

**Comment by XibalbaTM** [comment]
http://pokecrot.com/ this cheat working fine

**Comment by pokemonbotter** [comment]
that pokecrot is %100 a virus don't download it

**Comment by pokemonbotter** [comment]
This program is having errors they are making changers the coder will update when he can
BTW i think this is the best and safest bot I'm level 24 in 3 days

**Comment by Acerbytas** [comment]
Now when trying to Ptc login, an error called something like: ArgumentOutOfRangeException restarting. pulls out and force me to restart again and again. Uhhhh :(

**Comment by cyberguy91** [comment]
I'm also getting null refference and argumentoutofrangeexception - restarting. Sometimes it just spits out a bunch of code and says the program has crashed.

**Comment by kingkong91108** [comment]
Also getting the arguementoutofrangeexception.

**Comment by itskaje** [comment]
Me too
