### ISSUE TITLE
argument out of range exception

### ISSUE THREAD

**Issue by itskaje** [shiftcodeYT/PokeBot2#91]
The bot keeps saying: "argument out of range exception restarting" over and over... what do I do?

**Comment by leichterleben** [comment]
Same issue here. Started yesterday. Worked flawlessly before. Servers are up and running. Login works, evolving of P and discarding items works. As soon as the bot starts moving the error appears. Tried different locations and redownloading the software.

**Comment by gijsoman** [comment]
Yeah i have got the same problem too. 
First it was the google auth problem.
I think now it's just a problem with the ptc to?

anyway nice bot man!

**Comment by Kidades** [comment]
Waiting for fix
